# Generated by Django 5.0.4 on 2024-08-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('last_7_day_sale', models.IntegerField(blank=True, null=True)),
                ('available_skus', models.JSONField()),
                ('fit', models.CharField(max_length=255)),
                ('fabric', models.CharField(max_length=255)),
                ('neck', models.CharField(max_length=255)),
                ('sleeve', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
